"""author added

Revision ID: 89288d5d4e81
Revises: 1e0faf50155e
Create Date: 2023-01-17 20:09:07.238895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89288d5d4e81'
down_revision = '1e0faf50155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
